spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookbook
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true
    show-sql: true
