spring:
  mvc:
    async:
      request-timeout: 300000
  datasource:
    url: jdbc:postgresql://localhost:5432/cookbook
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true
    show-sql: true

  ai:
    ollama:
      chat:
        model: llava